kramdown:
  input: GFM
permalink: pretty
title: DroneDiego
email: mail@dronediego.com
description: San Diego from above. Get the perspective you need.
baseurl: # the subpath of your site, e.g. /blog/
baseurl: 
url: "http://dronediego.com" # the base hostname & protocol for your site

# User setting
owner: Drone Diego
email: DroneDiego@gmail.com
facebook_username: dronediego
twitter_username: dronediego
address:
  - line: San Diego
  - line: Southern California
  # Feel free to add more lines here 
telephone: (619) 387-8332
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown

sass:
  sass_dir: css/_scss

exclude:
- CNAME
- Gemfile
- LICENSE
- Rakefile
- README.md
- vendor/
- vnu/
- vnu.zip

layouts_dir: ./_layouts
lang: en

gems:
    - github-pages
    - jekyll-seo-tag

compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]