# Site settings
title: DroneDiego
email: mail@dronediego.com
description: > # this means to ignore newlines until "baseurl:"
  San Diego from above. Get the perspective you need.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: 
email: mail@dronediego.com
facebook_username:
twitter_username:
github_username:
address:
  - line: San Diego
  - line: Southern California
  # Feel free to add more lines here 
telephone: (800) 765-4321
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown